### PR TITLE
adding a Micro SD card socket (Wurth 693072010801)

### PR DESCRIPTION
**Pull request by hyOzd**
microsdfootprint

Datasheet: http://katalog.we-online.de/em/datasheet/693072010801.pdf

There are two points I'm not sure of:
1. I've added a detailed representation of metal shield and micro sd card to the F.Fab drawing layer, to make sure footprint is correctly positioned. Is that okay?
2. Bottom silk screen line is intentionally missing. My thinking was; "this side will be on the board edge and it won't be seen anyway".

### CODE REVIEW

**Comment by hackscribble** [comment]
Closing and re-opening to trigger Travis checks.

**Comment by hackscribble** [comment]
@SchrodingersGat are submissions still being accepted for `Sockets.pretty` or should this be moved over to `Connectors.pretty`?

**Comment by evanshultz** [comment]
@SchrodingersGat See above. Without a `Connectors_Wuerth`, should this go in `Connectors`?

Also, is Travis watching this repo? I don't see his feedback above.

**Comment by SchrodingersGat** [comment]
Travis is unaware of this one, I think.

Should we have a `Connectors_Card` for SD / SIM etc?

**Comment by SchrodingersGat** [comment]
Ok, executive decision time. Please move this to the [Connectors_Card.pretty repo](https://github.com/KiCad/Connectors_Card.pretty)

**Comment by hyOzd** [comment]
[Done](https://github.com/KiCad/Connectors_Card.pretty/pull/1)

**Comment by evanshultz** [comment]
@hyOzd I'm closing this case since these parts have been merged into the other library.

**Pull request closed without merging**
