### PR TITLE
Add TE 1746530-4

### PR DESCRIPTION
**Pull request by sclukey**
This is a 200 pin SODIMM DDR2 socket ([link here](http://www.te.com/usa-en/product-5-1746530-4.html)). The footprint is based off [this document](http://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Customer+Drawing%7F1746530%7FD1%7Fpdf%7FEnglish%7FENG_CD_1746530_D1.pdf%7F5-1746530-4).

This footprint includes a 3D model that is part of a pull request in the main kicad-library repo (KiCad/kicad-library#298).

### CODE REVIEW

**Comment by sclukey** [comment]
I removed the 3D model

**Comment by ricardocrudo** [comment]
@sclukey Can you please make some adjustments according [KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention)?

**Comment by hackscribble** [comment]
Hi @sclukey

**Comment by hackscribble** [comment]
Hi @sclukey 

Sorry your pull request got forgotten for so long. If you are still interested in contributing, please open a new pull request (in synch with the current master branch) and check your contribution against the latest KiCad Library Convention here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

Many thanks

**Pull request closed without merging**
